apiVersion: api.core.appnet.io/v1
kind: AppNetConfig
metadata:
  name: sample-ping
spec:
  appName: ping-pong-app
  appManifestFile: <APPNET_DIR_PATH>/compiler/examples/applications/ping-pong-app/ping-pong-app.yaml
  clientService: frontend
  serverService: ping
  method: PingEcho
  clientChain:
    - name: fault
      file: <APPNET_DIR_PATH>/compiler/examples/elements/ping_elements/fault.adn
      parameters:
        probability: "0.02"
    - name: logging
      file: <APPNET_DIR_PATH>/compiler/examples/elements/ping_elements/logging.adn
  serverChain:
    - name: acl
      file: <APPNET_DIR_PATH>/compiler/examples/elements/ping_elements/acl.adn
      parameters:
        body: apple
  anyChain:
    - name: metrics
      file: <APPNET_DIR_PATH>/compiler/examples/elements/ping_elements/metrics.adn
  proto: <APPNET_DIR_PATH>/compiler/examples/proto/ping.proto
